#!/usr/bin/env bash
# Build the Rust core for Android and stage it into the app's jniLibs.
#
# Kept as a script rather than a Gradle task on purpose: the NDK is a large,
# optional dependency, and the app is designed to build and run without it.
# Wiring this into Gradle would make a 2 GB download mandatory for anyone who
# only wants to work on the UI.
set -euo pipefail
cd "$(dirname "$0")/.."

# Locate the NDK. Cargo needs an absolute path to a per-ABI clang wrapper, and
# that path is specific to this machine — so `.cargo/config.toml` is generated
# here and git-ignored rather than committed. Hardcoding it would break the
# build for everyone else and for CI.
NDK="${ANDROID_NDK_HOME:-${ANDROID_NDK_ROOT:-}}"
if [ -z "$NDK" ]; then
    SDK="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/Android/Sdk}}"
    NDK=$(find "$SDK/ndk" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | sort -V | tail -1)
fi
if [ -z "$NDK" ] || [ ! -d "$NDK" ]; then
    echo "No Android NDK found. Set ANDROID_NDK_HOME, or install one with:" >&2
    echo "  sdkmanager --install 'ndk;27.2.12479018'" >&2
    exit 1
fi

BIN="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin"
[ -d "$BIN" ] || BIN="$NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin"

# API 23 matches the app's minSdk. The NDK ships one clang wrapper per
# (arch, API level); picking a higher one here would quietly raise the floor.
mkdir -p .cargo
cat > .cargo/config.toml <<EOF
# GENERATED by scripts/build-jni.sh — do not commit, do not edit.
[target.aarch64-linux-android]
linker = "$BIN/aarch64-linux-android23-clang"

[target.armv7-linux-androideabi]
linker = "$BIN/armv7a-linux-androideabi23-clang"

[target.x86_64-linux-android]
linker = "$BIN/x86_64-linux-android23-clang"
EOF
echo "==> NDK: $NDK"

declare -A ABI=(
  [aarch64-linux-android]=arm64-v8a
  [armv7-linux-androideabi]=armeabi-v7a
  [x86_64-linux-android]=x86_64
)

for target in "${!ABI[@]}"; do
  echo "==> $target"
  cargo build -p superfind-jni --release --target "$target"
  dest="android/app/src/main/jniLibs/${ABI[$target]}"
  mkdir -p "$dest"
  cp "target/$target/release/libsuperfind_jni.so" "$dest/"
done

echo "==> staged:"
find android/app/src/main/jniLibs -name '*.so' -exec ls -la {} \; | awk '{print "   " $5 "\t" $9}'
